// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Sinon           = require("wonder-bs-sinon/lib/js/src/sinon.js");
var Sinon$1         = require("sinon");
var Wonder_jest     = require("wonder-bs-jest/lib/js/src/wonder_jest.js");
var ConverImportCss = require("../../src/converImportCss/converImportCss.js");

describe("create shunk system file", (function () {
        var sandbox = Sinon.getSandboxDefaultVal(/* () */0);
        beforeEach((function () {
                sandbox[0] = Sinon$1.sandbox.create();
                return /* () */0;
              }));
        return Wonder_jest.test("add private functions", (function () {
                      ConverImportCss.convert("./libs/es6_global/src");
                      return Wonder_jest.Expect[/* toEqual */12](1)(Wonder_jest.Expect[/* expect */0](1));
                    }));
      }));

/*  Not a pure module */
