// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_array             = require("bs-platform/lib/js/caml_array.js");
var ExcepetionHandleSystem = require("../external/excepetionHandleSystem.js");

function createEmpty() {
  return /* array */[];
}

function flatten(arr) {
  return arr.reduce((function (a, b) {
                return a.concat(b);
              }), /* array */[]);
}

function getFirst(arr) {
  var match = arr.length;
  if (match !== 0) {
    return Caml_array.caml_array_get(arr, 0);
  } else {
    return ExcepetionHandleSystem.throwMessage("getFirst:the array is empty");
  }
}

exports.createEmpty = createEmpty;
exports.flatten     = flatten;
exports.getFirst    = getFirst;
/* No side effect */
