// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Fs         = require("fs");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

var changePathCode = "const getSnapshotPath = exports.getSnapshotPath = testPath => {\n    let filePathArray = testPath.split('/');\n    filePathArray.splice(5, 2);\n    testPath = filePathArray.join('/');\n    return _path2.default.join(\n      _path2.default.join(_path2.default.dirname(testPath), '__snapshots__'),\n      _path2.default.basename(testPath) + '.' + SNAPSHOT_EXTENSION)\n  };";

function changeSnapShotPath(filePath) {
  var pathRe = (/const\s*getSnapshotPath.*([^.].*){4}/g);
  var value = Fs.readFileSync(filePath, "utf8");
  var match = pathRe.exec(value);
  var resultFile;
  if (match !== null) {
    var res = Caml_array.caml_array_get(match, 0);
    var len = res.length;
    var index = value.indexOf(res);
    var start = value.slice(0, index);
    var end_ = value.slice(index + len | 0, value.length);
    resultFile = start + changePathCode + end_;
  } else {
    resultFile = value;
  }
  Fs.writeFileSync(filePath, resultFile);
  console.log("change snapshot path success : " + filePath);
  return /* () */0;
}

exports.changePathCode     = changePathCode;
exports.changeSnapShotPath = changeSnapShotPath;
/* fs Not a pure module */
